inherit_from:
  - .rubocop_todo.yml

require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.0 # or your Ruby version
  Exclude:
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'tmp/**/*'

Rails:
  Enabled: true
